import { EstimationReport as EstimationReportType } from './types';
export const MOCK_ESTIMATION_REPORT: EstimationReportType = {
  estimation: {
    total_effort: 120.02,
    duration: 20.4,
    team_size: 5.9,
    confidence_level: 'Medium',
    model_estimates: {
      cocomo: 100.0,
      cocomo_name: 'COCOMO II',
      cocomo_confidence: 70,
      cocomo_type: 'COCOMO',
      cocomo_description: 'Constructive Cost Model II estimation',
      function_points: 120.0,
      function_points_name: 'Function Points',
      function_points_confidence: 75,
      function_points_type: 'Function Points',
      function_points_description: 'Function Point Analysis based estimation',
      use_case_points: 150.0,
      use_case_points_name: 'Use Case Points',
      use_case_points_confidence: 70,
      use_case_points_type: 'Use Case',
      use_case_points_description: 'Use Case Points based estimation',
      loc_linear: 43.97,
      loc_linear_name: 'LOC Linear',
      loc_linear_confidence: 78,
      loc_linear_type: 'LOC',
      loc_linear_description: 'Lines of Code based Linear Regression model',
      loc_random_forest: 56.45,
      loc_random_forest_name: 'LOC Random Forest',
      loc_random_forest_confidence: 82,
      loc_random_forest_type: 'LOC',
      loc_random_forest_description: 'Lines of Code based Random Forest model',
      ml_Random_Forest: 112.53,
      ml_Random_Forest_name: 'ML Model',
      ml_Random_Forest_confidence: 70,
      ml_Random_Forest_type: 'ML',
      ml_Random_Forest_description: 'Estimation from ml_Random_Forest',
      ml_Gradient_Boosting: 371.52,
      ml_Gradient_Boosting_name: 'ML Model',
      ml_Gradient_Boosting_confidence: 70,
      ml_Gradient_Boosting_type: 'ML',
      ml_Gradient_Boosting_description: 'Estimation from ml_Gradient_Boosting',
      ml_Decision_Tree: 33.65,
      ml_Decision_Tree_name: 'ML Model',
      ml_Decision_Tree_confidence: 70,
      ml_Decision_Tree_type: 'ML',
      ml_Decision_Tree_description: 'Estimation from ml_Decision_Tree',
      ml_Linear_Regression: 371.52,
      ml_Linear_Regression_name: 'ML Model',
      ml_Linear_Regression_confidence: 70,
      ml_Linear_Regression_type: 'ML',
      ml_Linear_Regression_description: 'Estimation from ml_Linear_Regression',
    },
  },
  analysis: {
    cocomo: {
      size: 36.6,
      reliability: 1.15,
      complexity: 1.2,
      documentation: 1.0,
      reuse: 0.0,
      time_constraint: 1.0,
      platform_volatility: 1.1,
      storage_constraint: 1.0,
      personnel_capability: 1.0,
      personnel_experience: 1.0,
      tool_experience: 1.0,
      language_experience: 1.0,
      team_cohesion: 1.0,
      process_maturity: 1.0,
    },
    function_points: {
      external_inputs: 2,
      external_outputs: 2,
      external_inquiries: 1,
      internal_files: 1,
      external_files: 111,
      complexity_multiplier: 1.2,
    },
    use_case_points: {
      simple_actors: 19,
      average_actors: 19,
      complex_actors: 10,
      simple_use_cases: 2,
      average_use_cases: 4,
      complex_use_cases: 3,
      technical_factors: 0.98,
      environmental_factors: 1.13,
    },
    loc_linear: {
      kloc: 12.6,
      loc: 12600.0,
      complexity: 1.38,
      developers: 3,
      experience: 1.0,
      tech_score: 1.15,
    },
    loc_random_forest: {
      kloc: 12.6,
      loc: 12600.0,
      complexity: 1.38,
      developers: 3,
      experience: 1.0,
      tech_score: 1.15,
    },
    ml_features: {
      developers: 3,
      team_exp: 3,
      manager_exp: 3,
      size: 123.84,
      kloc_per_dev: 41.28,
      time_months: 6,
      kloc_per_month: 20.64,
      points_non_adjust: 809,
      adjustment: 1.2,
      transactions: 133.0,
      entities: 129,
      fp_per_month: 134.83333333333334,
      fp_per_dev: 269.6666666666667,
      schema: 1,
      complexity: 1.0,
    },
    requirements: [
      {
        id: 'REQ-1',
        text: '=== Project Report: CMMI, ISO, SDLC, ITIL, SCRUM Project Overview () === I. Thông tin chung - ID: PROJ-1 - Tên: CMMI, ISO, SDLC, ITIL, SCRUM Project Overview - Key: - Owner: user-123 - Mô tả: A comprehensive overview of CMMI, ISO, SDLC, ITIL, and SCRUM methodologies, including key concepts, differences, and applications, presented in a question-and-answer format.',
        type: 'interface',
      },
      {
        id: 'REQ-2',
        text: '- Created At: 2025-12-01T16:28:51Z - Updated At: 2025-12-01T16:28:51Z III.',
        type: 'functional',
      },
      {
        id: 'REQ-3',
        text: 'Thống kê Issues - Tổng số issues: 30 - Issues theo trạng thái: • To do [TODO]: 0 issue(s) • In progress [IN_PROGRESS]: 0 issue(s) • Done [DONE]: 0 issue(s) - Issues theo loại: • Epic (hierarchy=2): 0 • Story (hierarchy=1): 0 • Bug (hierarchy=1): 0 • Task (hierarchy=1): 0 • Sub-task (hierarchy=0): 0 IV.',
        type: 'general',
      },
      {
        id: 'REQ-5',
        text: '[CMMI-Q1] How many maturity levels does CMMI have, and what is the significance of each level?',
        type: 'interface',
      },
      {
        id: 'REQ-6',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: Answer: CMMI has 5 maturity levels: 1.',
        type: 'interface',
      },
      {
        id: 'REQ-9',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: Answer: Managed Process (Level 2) Processes are planned, monitored, and controlled at the project level.',
        type: 'interface',
      },
      {
        id: 'REQ-11',
        text: '[CMMI-Q3] Why do organizations aiming for Level 5 need strong investment in process measurement and continuous improvement?',
        type: 'functional',
      },
      {
        id: 'REQ-12',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: Answer: At Level 5 – Optimizing, the organization: Focuses on root cause analysis of defects and issues.',
        type: 'interface',
      },
      {
        id: 'REQ-14',
        text: '[CMMI-Q4] Name one important Process Area from Level 2 and explain why it is necessary.',
        type: 'functional',
      },
      {
        id: 'REQ-15',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: Answer (example: Requirements Management – RM): Requirements Management (RM) is a key Process Area at Level 2.',
        type: 'interface',
      },
      {
        id: 'REQ-17',
        text: '[CMMI-Q5] What is the biggest limitation of CMMI when applied in Agile environments?',
        type: 'general',
      },
      {
        id: 'REQ-18',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: Answer: A major limitation is that traditional CMMI implementations: Are often document- and process-heavy, focusing ... 6.',
        type: 'functional',
      },
      {
        id: 'REQ-19',
        text: '[ISO-Q1] ISO 9001 is based on the PDCA cycle.',
        type: 'general',
      },
      {
        id: 'REQ-20',
        text: 'Which stage do you think has the most impact on output quality?',
        type: 'general',
      },
      {
        id: 'REQ-21',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: All stages (Plan-Do-Check-Act) are important, but “Plan\\" typically has the strongest impact on output quality.',
        type: 'interface',
      },
      {
        id: 'REQ-24',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: Answer: Corrective Action Taken after a nonconformity or incident has occurred.',
        type: 'interface',
      },
      {
        id: 'REQ-25',
        text: 'Goal: eliminate the cause of an exist... 8.',
        type: 'general',
      },
      {
        id: 'REQ-26',
        text: '[ISO-Q3] ISO 27001 requires periodic risk assessment.',
        type: 'interface',
      },
      {
        id: 'REQ-27',
        text: 'Why must this activity be performed regularly - Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: Risk assessment must be regular because: The environment changes: new technologies, new threats, new vulnerabilities,... 9.',
        type: 'functional',
      },
      {
        id: 'REQ-28',
        text: '[ISO-Q4] Why is the SoA (Statement of Applicability) a mandatory document in ISO 27001?',
        type: 'data',
      },
      {
        id: 'REQ-29',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: Answer: The Statement of Applicability (SoA): Lists all information security controls that are applied or excluded, u... 10.',
        type: 'interface',
      },
      {
        id: 'REQ-30',
        text: '[ISO-Q5] List 3 common information security violations that occur in schools/universities.',
        type: 'interface',
      },
      {
        id: 'REQ-31',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: Examples include: 1.',
        type: 'interface',
      },
      {
        id: 'REQ-32',
        text: 'Sharing accounts and passwords (students sharing LMS credentials with friends).',
        type: 'security',
      },
      {
        id: 'REQ-35',
        text: '[SDLC-Q1] What is the difference between Validation and Verification in software development?',
        type: 'general',
      },
      {
        id: 'REQ-36',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: Verification – “Build the product right\\" Checks whether the product is built according to the specified requirements... 12.',
        type: 'interface',
      },
      {
        id: 'REQ-37',
        text: '[SDLC-Q2] Why does the Waterfall model struggle when requirements change frequently?',
        type: 'interface',
      },
      {
        id: 'REQ-38',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: Waterfall: Has sequential phases: Requirements → Design → Implementation Testing → Deployment.',
        type: 'interface',
      },
      {
        id: 'REQ-40',
        text: '[SDLC-Q3] In Agile/Iterative models, why is Feedback considered the most important mechanism?',
        type: 'general',
      },
      {
        id: 'REQ-41',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: In Agile/Iterative models: The product is developed in short iterations/sprints.',
        type: 'interface',
      },
      {
        id: 'REQ-42',
        text: 'Each iteration delivers a working in... 14.',
        type: 'general',
      },
      {
        id: 'REQ-43',
        text: '[SDLC-Q4] Which SDLC phase contributes the most to the cost of fixing defects?',
        type: 'general',
      },
      {
        id: 'REQ-44',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: Defect fix cost increases over time: Defects found in production/operation are usually the most expensive to fix beca... 15.',
        type: 'interface',
      },
      {
        id: 'REQ-45',
        text: '[SDLC-Q5] Give an example of a project that failed because it skipped the Requirements Analysis phase.',
        type: 'interface',
      },
      {
        id: 'REQ-46',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: Example: A team builds a student attendance app: They skip proper requirements analysis with academic staff and stude... 16.',
        type: 'interface',
      },
      {
        id: 'REQ-48',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: Incident: An event that disrupts or degrades a service.',
        type: 'interface',
      },
      {
        id: 'REQ-50',
        text: '[ITIL-Q2] Why does ITIL focus on delivering service value rather than technology value?',
        type: 'general',
      },
      {
        id: 'REQ-51',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: Users and customers do not buy \\"servers, firewalls, databases\\"; they buy: Reliable email services, 24/7 online lear... 18.',
        type: 'data',
      },
      {
        id: 'REQ-53',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: One very important KPI is: MTTR - Mean Time To Restore/Resolve It is important because: Users care about how quickly ... 19.',
        type: 'interface',
      },
      {
        id: 'REQ-54',
        text: '[ITIL-Q4] Why does Change Management require a CAB (Change Advisory Board)?',
        type: 'interface',
      },
      {
        id: 'REQ-55',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: The Change Advisory Board (CAB): Includes representatives from different areas (IT operations, development, business,... 20.',
        type: 'interface',
      },
      {
        id: 'REQ-56',
        text: '[ITIL-Q5] What is the role of the Service Desk in improving user experience (UX)?',
        type: 'security',
      },
      {
        id: 'REQ-57',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: The Service Desk, as the single point of contact between users and IT, improves UX by: Receiving and handling inciden... 21.',
        type: 'interface',
      },
      {
        id: 'REQ-59',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: The Product Owner (PO) is responsible for maximizing product value by: Managing the Product Backlog (creating, refini... 22.',
        type: 'interface',
      },
      {
        id: 'REQ-60',
        text: '[SCRUM-Q2] What is a Sprint Goal, and why does the Scrum team need a clear one - Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: A Sprint Goal is a concise statement of what the team wants to achieve in a Sprint.',
        type: 'interface',
      },
      {
        id: 'REQ-61',
        text: 'Example: \\"Enable students to reg... 23.',
        type: 'functional',
      },
      {
        id: 'REQ-62',
        text: '[SCRUM-Q3] Why can the Sprint Backlog change during the Sprint but the Sprint Goal cannot - Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: The Sprint Goal is the strategic direction for the Sprint and should remain stable to maintain focus and predictabili... 24.',
        type: 'functional',
      },
      {
        id: 'REQ-63',
        text: '[SCRUM-Q4] How does the Daily Scrum help the team detect problems early?',
        type: 'general',
      },
      {
        id: 'REQ-64',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: During the Daily Scrum, each team member typically shares: What they did, What they plan to do, Any impediments they ... 25.',
        type: 'interface',
      },
      {
        id: 'REQ-65',
        text: '[SCRUM-Q5] What is the difference between the Product Backlog and the Sprint Backlog - Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: Product Backlog: Ordered list of everything that might be needed in the product (features, bugs, technical work).',
        type: 'functional',
      },
      {
        id: 'REQ-69',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: No.',
        type: 'interface',
      },
      {
        id: 'REQ-71',
        text: 'Focuses on: Ensuring Scrum is understood and used correctly, R... 27.',
        type: 'interface',
      },
      {
        id: 'REQ-72',
        text: '[SCRUM-Q7] How does the Definition of Done (DoD) improve product quality?',
        type: 'general',
      },
      {
        id: 'REQ-73',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: The Definition of Done (DoD) is a shared, explicit checklist of criteria that an item must meet to be considered \\"do... 28.',
        type: 'functional',
      },
      {
        id: 'REQ-75',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: During the Sprint Review: The team demonstrates the Increment to stakeholders.',
        type: 'interface',
      },
      {
        id: 'REQ-76',
        text: 'Stakeholders: See working software, Pr... 29.',
        type: 'general',
      },
      {
        id: 'REQ-77',
        text: '[SCRUM-Q9] Scrum allows requirement changes during the project—what are the limits of this flexibility - Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: Scrum is flexible but not chaotic: Within a running Sprint: The Sprint Goal must not change.',
        type: 'interface',
      },
      {
        id: 'REQ-78',
        text: 'The Sprint Backlog can c... 30.',
        type: 'general',
      },
      {
        id: 'REQ-79',
        text: '[SCRUM-Q10] Give an example of a project that may fail without an effective Sprint Retrospective.',
        type: 'general',
      },
      {
        id: 'REQ-80',
        text: '- Loại: N/A | Trạng thái: N/A | Priority: N/A - Reporter: N/A | Assignee: N/A - Story points: N/A | Parent: N/A - Dates: start=N/A, due=N/A, resolved=N/A - Mô tả: Example: A team develops an e-commerce application.',
        type: 'interface',
      },
      {
        id: 'REQ-81',
        text: 'Every Sprint, they: Miss commitments, Introduce recurring bugs, S...',
        type: 'general',
      },
    ],
    features: {
      size: 36.6,
      complexity: 1.2,
      reliability: 1.15,
      num_requirements: 61,
      functional_reqs: 9,
      non_functional_reqs: 36,
      has_security_requirements: true,
      has_performance_requirements: false,
      has_interface_requirements: true,
      has_data_requirements: true,
      entities: 97,
      technologies: ['rest', 'ai', 'go'],
      num_technologies: 3,
      text_complexity: 2.466666666666667,
    },
    confidence: {
      confidence_factors: {
        text_length: true,
        has_loc_estimate: false,
        has_sections: false,
        has_features: true,
        has_requirements: true,
        model_agreement: false,
      },
      confidence_explanation: 'Confidence is Medium based on 3 positive factors out of 6',
    },
  },
  document: {
    filename: 'estimation.txt',
    file_type: '.txt',
    size_bytes: 13181,
    text_length: 12055,
  },
};
