# yaml-language-server: $schema=https://api.cerbos.dev/latest/cerbos/policy/v1/Policy.schema.json
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: 'default'
  importDerivedRoles:
    - common_derived_roles
  resource: 'workspace'
  rules:
    # for workspace
    - actions: [read, view]
      effect: EFFECT_ALLOW
      derivedRoles:
        - ws_owner
        - ws_admin
        - ws_member

    - actions: [update]
      effect: EFFECT_ALLOW
      derivedRoles:
        - ws_owner
        - ws_admin

    - actions: [delete]
      effect: EFFECT_ALLOW
      derivedRoles:
        - ws_owner

    # for workspace.member
    - actions:
        - members:manage#member
      effect: EFFECT_ALLOW
      derivedRoles:
        - ws_owner
        - ws_admin

    - actions:
        - members:manage#admin
      effect: EFFECT_ALLOW
      derivedRoles:
        - ws_owner

    # for workspace.project
    - actions: [projects:create]
      effect: EFFECT_ALLOW
      derivedRoles:
        - ws_owner
        - ws_admin
